driver:
  name: vagrant
  customize:
    natdnsproxy1: 'on'
    natdnshostresolver1: 'on'

provisioner:
  name: puppet_apply
  # Not installing chef since inspec is used for testing
  require_chef_for_busser: false
  manifests_path: spec/fixtures/kitchen/manifests
  modules_path: spec/fixtures/kitchen/modules
  resolve_with_librarian_puppet: true
  ignore_spec_fixtures: true

verifier:
  name: inspec
  sudo: true
  reporter:
    - cli
    - json:./sec_results/inspec/%{platform}_%{suite}_<%= Time.now.strftime("%m-%d-%Y_%H:%M:%S") %>.json
  attr:
    - disable_slow_controls: true

platforms:
  - name: centos-7
    driver:
      box: centos/7

suites:
  - name: default
    provisioner:
      manifest: site.pp
    verifier:
      inspec_tests:
        # if you want to use your local code
        #- name: happy
        #  path: <%= ENV[('PWD')] %>/spec/fixtures/inspec_profiles/CentOS-7-disa_stig
        # If you want to use your local code on a Windows machine from the parent directory
        #- path: ./spec/fixtures/inspec_profiles/RedHat-7-disa_stig
        # if you want to use the current profile in the git repo
        - git: https://github.com/simp/inspec-profile-disa_stig-el7.git
      #controls:
      #  - V-72309
      attrs:
        - <%= ENV[('PWD')] %>/attributes.yml
